GET https://training.orocloud.com/

#Response: <html><body><script type="text/javascript" src="/aes.min.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;f<d.length;f++)e+=(16>d[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("c576a006517b6a4dc7cb536da1a16f05"),b=toNumbers("9a8a414dada4685fd59cf1567cf3444b"),c=toNumbers("35698a127fdd84883319aa7335d7ed78");document.cookie="OCXS="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/";document.location.href="https://training.orocloud.com/?12198c25561b02476436c9a957ec6d20=1";</script></body></html>